@startuml

package "server/src" {
  package "routes" {}
  package "controllers" {}
  package "services" {}
  package "models" {}
  package "middlewares" {}
  package "validations" {}
  package "config" {}
  package "constants" {}
}

database "MongoDB" {}

routes --> controllers : Routes to
routes --> middlewares : Uses
routes --> validations : Uses

controllers --> services : Calls (Optional)
controllers --> models : Interacts

services --> models : Interacts
middlewares --> models : Interacts

models --> MongoDB : Read/Write

config --> MongoDB : Configure Connection

@enduml
